### PR TITLE
Import multiple animation files

### PR DESCRIPTION
**Pull request by simonwashere**
reads in additional animations from multiple fbx files with numbers added to the base name (eg. test1.fbx, test2.fbx, ...)

### CODE REVIEW

**Comment by zellski** [comment]
Thanks for this! I will have a look when I've scraped my own PR off the floor.

Do you think we need to detect node name collision and report them to user, or is the stern warning in the documentation enough? It's sort of a power user feature, so that might be fine...

**Comment by simonwashere** [comment]
Yes that makes sense, I will add a warning if the node name is missing or duplicated for any node that has valid animation data.

**Comment by zellski** [comment]
Sorry, merging your other PR caused conflicts here.  :-)

**Comment by simonwashere** [comment]
@zellski I can't seem to build the project now, maybe am doing something stupid. It couldn't find boost headers so I tried to setup again from scratch with cmake and got this error:

CMake Error at CMakeLists.txt:21 (message):
  The Conan package manager must run ('install') first.  Example usage:
    > mkdir -p build_debug
    > conan install . -i build_debug -s build_type=Debug -e FBXSDK_SDKS=/home/zell/FBXSDK
    > conan build . -bf build_debug

**Comment by zellski** [comment]
@simonwashere Aye, things got a little hasty this weekend and I merged a PR that changes the build system quite a bit. I have a TODO to fix up the README.md with new detailed instructions.

Briefly, though, you need to install Python 3.x if you don't have it, install 'pip' if you don't have it, then on a command line, i.e. 'pip install conan'. After that you should be able to follow those CMake directions.

Conan will download precompiled Boost library (and header) files and set CMake up properly with pats. Once the initial setup is done, it's actually pretty wonderful.

**Comment by InnoLuke** [comment]
What's happening with this PR? This feature would be extremely valuable to me

**Comment by kungfooman** [comment]
@simonwashere You got it to work again?

I would love this... fbx files often come like this:

image

**Comment by simonwashere** [comment]
Sorry, I haven't looked at this in ages, they changed the build system and it no longer compiled on my machine :(
Might try and have another go at some point, but can't promise if/when I will get around to it

**Comment by kungfooman** [comment]
Thanks for the feedback @simonwashere

Too bad when good PR's are not merged in time and then nobody else with write access solves the conflicts

**Comment by AmitMY** [comment]
@BluEagle any chance of merging?

**Pull request closed without merging**
