### PR TITLE
KHR_materials_unlit

### PR DESCRIPTION
**Pull request by robertlong**
Adds support for the pending [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/pull/1163) glTF extension.

Todo:
- [ ] Rename variables using the old `KHR_materials_common` extension

### CODE REVIEW

**Comment by zellski** [comment]
Thank you very much, @robertlong -- at a cursory glance this looks great; I'll do a final eyeballing in the weekend and push out a new build.

**Comment by zellski** [comment]
... soon. Work madness.

**Comment by robertlong** [comment]
Oh great, thanks!

**Comment by yosun** [comment]
Is this still working in the latest patch executable?

**Pull request merged**
