### PR TITLE
Move to C++17 and std::filesystem.

### PR DESCRIPTION
**Pull request by zellski**
With this PR, we get rid of all the increasingly broken file system utility code, and trust instead std::filesystem to place all the cross-platform complexity behind a well-defined API.

Unfortunately, even with mostly C++17 compliant toolchains, std::filesystem support remains a little elusive; it is well supported in Visual Studio (especially 2019), but not by default in Mac OS X, and even in GCC 8.0 it requires an explicit '-l c++fs'.

This PR also silences some of the more egregious compiler warnings, mostly by being explicit about where we cast to the uint32 types glTF prefers, updates the README a bit, and replaces much of the code that tries to match textures in the FBX with ones in the filesystem.

### CODE REVIEW

**Comment by jfaust** [comment]
Does this mean we won't be able to build FBX2glTF with the standard clang compiler bundled with Xcode? Seems problematic to force installation of a different compiler.

**Comment by zellski** [comment]
@jfaust It's certainly not ideal, but I mostly lay that at Apple's feet. However, I will look into a Boost.Filesystem solution.

**Comment by jfaust** [comment]
`boost` on OSX and `std` where it's supported seems reasonable.

PS. this caught my eye because we build FBX2glTF as a library and use it that way instead of as a command-line tool, so using a different compiler to build the 1 library isn't super easy. Thanks for being flexible.

**Comment by zellski** [comment]
Continued in https://github.com/facebookincubator/FBX2glTF/pull/180.

**Pull request closed without merging**
