### PR TITLE
Add option "--fbx-tmp-dir"

### PR DESCRIPTION
**Pull request by shrinktofit**

### CODE REVIEW

**Comment by shrinktofit** [comment]
Sometimes user might not expect `.fbm` directory to be auto-generated into FBX file's directory.

**Comment by zellski** [comment]
Thanks very much! Yes, it’s frustrated me at times that the SDK writes next to the source, which ought to be considered a R/O area. Looks like you might also have helped with non-ascii source files? Will verify and merge later today.

**Comment by shrinktofit** [comment]
>  Looks like you might also have helped with non-ascii source files? 

Yes. The `fbxFileName` is encoded as ANSI or Unicode in Windows. But `FBXImporter::Initialize` requires UTF-8 encoding. (For me, "Failed to load FBX file" if CJK path passed to command line.)

**Comment by zellski** [comment]
@shrinktofit About to merge this, but now I'm thinking perhaps we should improve the default behaviour? For example:
- `--fbx-tmp-dir-mode={auto/sdk/explicit}`:
  - `auto` is default, and means call e.g. `boost::temp_directory_path()`
  - `sdk` is current behaviour
  - `explicit` requires --fbx-tmp-dir switch, as per your PR

**Pull request merged**
